printNumbers: printNumbers.c
	gcc printNumbers.c -o printNumbers
printPrimes: printPrimes.c
	gcc printPrimes.c -o printPrimes
test: printNumbers printPrimes
	./printNumbers | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes | ./printPrimes